<a href="https://colab.research.google.com/github/nikhil00shinde/Data-Science/blob/main/22-07-01-Numpy/Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# Basics

Create from python list
* size
* dtype
* shape
* ndim

**Performance**
* memory
* time

In [ ]:
l = np.array([1,2,5,6,7])
print(l)

[1 2 5 6 7]


In [ ]:
print("Type",type(l))
print('Size',l.size)
print('dtype',l.dtype)

Type <class 'numpy.ndarray'>
Size 5
dtype int64


Dtypes: https://numpy.org/devdocs/user/basics.types.html
* int
* uint
* float {8,16,32,64}

In [ ]:
# l = np.array([1,2,5,6,70000],dtype='int8)
l = np.array([1,2,5,6.,9,700000])

print(l.dtype)
print(l)

float64
[1.e+00 2.e+00 5.e+00 6.e+00 9.e+00 7.e+05]


e + x => 10^x

In [ ]:
l = np.array([1,2,5,6.6,9],dtype='int32')

print(l.dtype)
print(l)

int32
[1 2 5 6 9]


## Performance

**Memory**

In [ ]:
import sys

a = 9
print('Bits',sys.getsizeof(a)*8)

Bits 224


In [ ]:
a = np.array([3,5,8,5])

print(a.dtype)
print('Storage of 1 data int Bits\'s',a.itemsize*8)
print('Storage of complete array in bit\'s', a.nbytes*8)

int64
Storage of 1 data int Bits's 64
Storage of complete array in bit's 256


**Time**

In [ ]:
ar = np.arange(2,100002)
print(ar.size)

100000


In [ ]:
s = 0
for i in ar:
  s = s+i
print(s)

5000150000


In [ ]:
def sumArray(l):
  sum = 0
  for i in l:
    sum = sum + i
  return sum

%timeit sumArray(ar) # python function

100 loops, best of 5: 10.8 ms per loop


In [ ]:
%timeit ar.sum() # numpy function

The slowest run took 8.63 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 5: 71.4 µs per loop


# Numpy array from Scratch

* `np.zeros(size)`
* `np.ones(size)`
* `np.full(size,value)` # repeats 7 10 times
* `np.arange(start,stop,step)`

In [ ]:
ar = np.zeros(10,dtype=np.int32)
print(ar)
print(ar.dtype)
print(ar.size)

[0 0 0 0 0 0 0 0 0 0]
int32
10


In [ ]:
ar = np.ones(10,dtype=np.int32)
print(ar)
print(ar.dtype)
print(ar.size)

[1 1 1 1 1 1 1 1 1 1]
int32
10


In [ ]:
ar = np.full(10,7,dtype=np.int32) # repeats
print(ar)
print(ar.dtype)
print(ar.size)

[7 7 7 7 7 7 7 7 7 7]
int32
10


In [ ]:
print(list(range(20,9,-2)))
ar = np.arange(20,9,-2)
print(ar)

[20, 18, 16, 14, 12, 10]
[20 18 16 14 12 10]


# Slicing / Indexing

* Same as python list

In [ ]:
ar = np.arange(2,10) 
print(ar)
print(ar.size)

[2 3 4 5 6 7 8 9]
8


In [ ]:
print(ar[0])
print(ar[-2])

2
8


In [ ]:
ar[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2])

Task


1. https://www.hackerrank.com/challenges/np-arrays/problem?isFullScreen=true
2. https://www.hackerrank.com/challenges/np-zeros-and-ones/problem?isFullScreen=true


```
def arrays(arr):
  l = arr[::-1];
  l = numpy.array(l,float)
  return l

import numpy

s = input()
l = s.split(' ') # ['3', '3', ...... '3]

for i in range(len(l)):
  l[i] = int(l[i])

print(numpy.zeros(l, dtype='int8'))
print(numpy.ones(l, dtype='int8'))
```

In [ ]:
# without using full function +
ar = np.ones(12)*8
print(ar)
print(ar.size)
print(ar.dtype)

[8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
12
float64


# Deep copy & Shallow copy

Python does not reflects changes in original array

Numpy does
 * To prevent we can use `ar.copy()`

In [1]:
l = list(range(10))
sl = l[3:8]
print(l)
print(sl)

print('changing')
sl[0] = 8
print(l)
print(sl)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[3, 4, 5, 6, 7]
changing
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[8, 4, 5, 6, 7]


In [7]:
ar = np.arange(10)
sl = ar[3:8]
print(ar)
print(sl)

print('changing')
sl[0] = 8
print(ar)
print(sl)

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6 7]
changing
[0 1 2 8 4 5 6 7 8 9]
[8 4 5 6 7]


In [6]:
ar = np.arange(10)
sl = ar[3:8].copy()
print(ar)
print(sl)

print('changing')

sl[0] = 8

print(ar)
print(sl)

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6 7]
changing
[0 1 2 3 4 5 6 7 8 9]
[8 4 5 6 7]


# Multi Dimension

multi dim = Array inside another array

* ndim 
* shape : length of all array one inside other

**Create from Scratch**

**Indexing/Slicing**

In [8]:
ar = np.array([1,2,3,4])
print(type(ar))
print(ar.ndim)
print(ar.shape)

<class 'numpy.ndarray'>
1
(4,)


In [9]:
ar = np.array([ [1,2], [3,4], [4,5], [6,7]])

print(ar)
print(ar.ndim)
print(ar.shape)
print(ar[0])
print(ar[1])

[[1 2]
 [3 4]
 [4 5]
 [6 7]]
2
(4, 2)
[1 2]
[3 4]


In [12]:
ar = np.array([ [[1,1,1], [2,1,1]], [[3,1,1],[4,1,1]], [[4,1,1],[5,1,1]], [[6,1,1],[7,1,1]] ])

print(ar.ndim)
print(ar.shape)
print(ar.size) # count of values{int, float}
print(len(ar), len(ar[0]), len(ar[0][0]))

3
(4, 2, 3)
24
4 2 3


In [13]:
print(ar)

[[[1 1 1]
  [2 1 1]]

 [[3 1 1]
  [4 1 1]]

 [[4 1 1]
  [5 1 1]]

 [[6 1 1]
  [7 1 1]]]


In [14]:
print(ar[0][1][0])
print(ar[0, 1, 0])

2
2


## from Scratch


*   `np.ones( (2,5,3) )`
*   `np.zeros( (2,5,3) )`
*   `np.arange(12).reshape(3,-1)`
*   full



In [15]:
ar = np.ones( (2,5,3))

print(ar)
print(ar.ndim)
print(ar.shape)
print(ar.size)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
3
(2, 5, 3)
30


In [16]:
a = ar.reshape(3, 5, 2)

print(a)
print(a.ndim)
print(a.shape)
print(a.size)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]
3
(3, 5, 2)
30


In [18]:
a = ar.reshape(3, -1)

print(a)
print(a.ndim)
print(a.shape)
print(a.size)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
2
(3, 10)
30


In [19]:
ar = np.arange(12)
print(ar)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [20]:
ar.reshape(-1, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

## Indexing / Slicing

* `grid[8, 9, 3]`
* `grid[3:9, 9]`

In [21]:
ar = np.arange(12).reshape(3,-1)

print(ar.shape)
print(ar)

(3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [22]:
print(ar[1])

ar[1, 2]

[4 5 6 7]


6

In [23]:
print(ar)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [28]:
print(ar[0:2])
print()
print(ar[0:2, 1:])
print()
print(ar[0:2, :0:-1])

[[0 1 2 3]
 [4 5 6 7]]

[[1 2 3]
 [5 6 7]]

[[3 2 1]
 [7 6 5]]
