<a href="https://colab.research.google.com/github/nikhil00shinde/Data-Science/blob/main/22-01-07-Numpy/Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Basics

Create from python list
* size
* dtype
* shape
* ndim

**Performance**
* memory
* time

In [3]:
l = np.array([1,2,5,6,7])
print(l)

[1 2 5 6 7]


In [4]:
print("Type",type(l))
print('Size',l.size)
print('dtype',l.dtype)

Type <class 'numpy.ndarray'>
Size 5
dtype int64


Dtypes: https://numpy.org/devdocs/user/basics.types.html
* int
* uint
* float {8,16,32,64}

In [6]:
# l = np.array([1,2,5,6,70000],dtype='int8)
l = np.array([1,2,5,6.,9,700000])

print(l.dtype)
print(l)

float64
[1.e+00 2.e+00 5.e+00 6.e+00 9.e+00 7.e+05]


e + x => 10^x

In [8]:
l = np.array([1,2,5,6.6,9],dtype='int32')

print(l.dtype)
print(l)

int32
[1 2 5 6 9]


## Performance

**Memory**

In [9]:
import sys

a = 9
print('Bits',sys.getsizeof(a)*8)

Bits 224


In [10]:
a = np.array([3,5,8,5])

print(a.dtype)
print('Storage of 1 data int Bits\'s',a.itemsize*8)
print('Storage of complete array in bit\'s', a.nbytes*8)

int64
Storage of 1 data int Bits's 64
Storage of complete array in bit's 256


**Time**

In [11]:
ar = np.arange(2,100002)
print(ar.size)

100000


In [12]:
s = 0
for i in ar:
  s = s+i
print(s)

5000150000


In [13]:
def sumArray(l):
  sum = 0
  for i in l:
    sum = sum + i
  return sum

%timeit sumArray(ar) # python function

100 loops, best of 5: 10.8 ms per loop


In [15]:
%timeit ar.sum() # numpy function

The slowest run took 8.63 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 5: 71.4 µs per loop


# Numpy array from Scratch

* `np.zeros(size)`
* `np.ones(size)`
* `np.full(size,value)` # repeats 7 10 times
* `np.arange(start,stop,step)`

In [16]:
ar = np.zeros(10,dtype=np.int32)
print(ar)
print(ar.dtype)
print(ar.size)

[0 0 0 0 0 0 0 0 0 0]
int32
10


In [17]:
ar = np.ones(10,dtype=np.int32)
print(ar)
print(ar.dtype)
print(ar.size)

[1 1 1 1 1 1 1 1 1 1]
int32
10


In [18]:
ar = np.full(10,7,dtype=np.int32) # repeats
print(ar)
print(ar.dtype)
print(ar.size)

[7 7 7 7 7 7 7 7 7 7]
int32
10


In [19]:
print(list(range(20,9,-2)))
ar = np.arange(20,9,-2)
print(ar)

[20, 18, 16, 14, 12, 10]
[20 18 16 14 12 10]


# Slicing / Indexing

* Same as python list

In [20]:
ar = np.arange(2,10) 
print(ar)
print(ar.size)

[2 3 4 5 6 7 8 9]
8


In [21]:
print(ar[0])
print(ar[-2])

2
8


In [22]:
ar[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2])

Task


1. https://www.hackerrank.com/challenges/np-arrays/problem?isFullScreen=true
2. https://www.hackerrank.com/challenges/np-zeros-and-ones/problem?isFullScreen=true


```
def arrays(arr):
  l = arr[::-1];
  l = numpy.array(l,float)
  return l

import numpy

s = input()
l = s.split(' ') # ['3', '3', ...... '3]

for i in range(len(l)):
  l[i] = int(l[i])

print(numpy.zeros(l, dtype='int8'))
print(numpy.ones(l, dtype='int8'))
```

In [23]:
# without using full function +
ar = np.ones(12)*8
print(ar)
print(ar.size)
print(ar.dtype)

[8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
12
float64
